name: CI and Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Code with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .

  trigger:
    name: Trigger Render Deploy Hook
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Call Render Deploy Hook
        run: |
          curl -X GET "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

  healthcheck:
    name: Check Render Deployment
    runs-on: ubuntu-latest
    needs: trigger
    steps:
      - name: Wait for Deployment
        run: sleep 20

      - name: Check if backend is live
        run: |
          curl -fsS https://kinderkunst-backend.onrender.com/health || exit 1
