name: Deploy Backend to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Render Deploy Hook
    runs-on: ubuntu-latest

    steps:
      - name: Call Render Deploy Hook
        run: |
          curl "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}