name: Deploy Backend to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      - name: Warten auf Deployment (Render braucht Zeit)
        run: sleep 60

      - name: Healthcheck
        run: |
          echo "Prüfe Verfügbarkeit unter https://kinderkunst-backend.onrender.com/health"
          curl --fail --retry 5 --retry-delay 10 https://kinderkunst-backend.onrender.com/health
